# Load needed modules

In [1]:
# modules:
import pandas as pd
import os
from openai import OpenAI


# get external variables or functions:
import src.API_key as key


from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI
from langchain.callbacks import get_openai_callback


import json

# Load data to translate
> this should be the drawn concept data set whereby 1 row is 1 drawn concept

In [4]:
print(os.getcwd())
# Get the current working directory
os.chdir("outputs/associations") 
directory = os.getcwd()

/home/fenn/Desktop/Publications/Article_HumanOversightAss/Article_humanOversightAssociations/Analyses

In [5]:
# print the current working directory
print(directory)

/home/fenn/Desktop/Publications/Article_HumanOversightAss/Article_humanOversightAssociations/Analyses/outputs/associations

In [6]:
# List files in the current working directory
files = os.listdir('.')
# Display the list of files
print(files)

['placeholder.txt', 'ass_study.xlsx', 'ass_study.csv', 'ass_study.rds']

In [7]:
# Load the .xlsx file into a DataFrame
df = pd.read_excel(directory + "/ass_study.xlsx")

# prepare the data frames 
# for the text only the unique values are kept
print("Number of rows/ colums:")
print(df.shape)

Number of rows/ colums:
(18960, 11)

In [9]:
df

,participant_id,study_condition,gender,age,cue,valence,response,response_position,response_level,timestamp,time_diff_sec
0,6914df322c0ecd3bdadf7251,Diagnostic,male,33.0,Diagnostic,6.0,Richtig,1,1,2025-11-24 08:16:27.162,0.000
1,6914df322c0ecd3bdadf7251,Diagnostic,male,33.0,Diagnostic,7.0,Fortschritt,2,1,2025-11-24 08:16:35.087,7.925
2,6914df322c0ecd3bdadf7251,Diagnostic,male,33.0,Diagnostic,5.0,Zukunft,3,1,2025-11-24 08:16:38.866,11.704
3,6914df322c0ecd3bdadf7251,Diagnostic,male,33.0,Diagnostic,6.0,Zusammenspiel,4,1,2025-11-24 08:16:46.704,19.542
4,6914df322c0ecd3bdadf7251,Diagnostic,male,33.0,Diagnostic,7.0,Verbesserung,5,1,2025-11-24 08:16:54.584,27.422
...,...,...,...,...,...,...,...,...,...,...,...
18955,69273d7a43eca09e260bac35,CourtDecision,female,22.0,Fragwürdig,NaN,wieso,1,2,2026-02-11 17:13:58.343,443.097
18956,69273d7a43eca09e260bac35,CourtDecision,female,22.0,Fragwürdig,NaN,künstlich,2,2,2026-02-11 17:14:07.421,452.175
18957,69273d7a43eca09e260bac35,CourtDecision,female,22.0,Fragwürdig,NaN,unsicher,3,2,2026-02-11 17:14:15.217,459.971
18958,69273d7a43eca09e260bac35,CourtDecision,female,22.0,Fragwürdig,NaN,schlecht,4,2,2026-02-11 17:14:22.131,466.885
18959,69273d7a43eca09e260bac35,CourtDecision,female,22.0,Fragwürdig,NaN,naja,5,2,2026-02-11 17:14:26.600,471.354

# test dictionary

In [10]:
# Exemplary dictionary
dictionary = {
    'Hallo': 'Hello',
    'Guten Tag': 'Good day',
    'Wie sagst es dir?': 'How are you?',
    'Ich bind eine Roboter.': 'I am a robot.',
    'Ich bin ein sozialer Flofods.': 'I am a social Flofods.'
}

dictionary.update({'AAA': 'BBB',  'Hallo': 'Hello',  'aaa': '111'})

# Convert the dictionary into a DataFrame
df_test = pd.DataFrame(list(dictionary.items()), columns=['German', 'English'])

# Display the DataFrame
print(df_test)

print(dictionary.keys())

                          German                 English
0                          Hallo                   Hello
1                      Guten Tag                Good day
2              Wie sagst es dir?            How are you?
3         Ich bind eine Roboter.           I am a robot.
4  Ich bin ein sozialer Flofods.  I am a social Flofods.
5                            AAA                     BBB
6                            aaa                     111
dict_keys(['Hallo', 'Guten Tag', 'Wie sagst es dir?', 'Ich bind eine Roboter.', 'Ich bin ein sozialer Flofods.', 'AAA', 'aaa'])

# Set up ChatGPT

## Translate written text new

In [11]:
json_schema = {
    "title": "Translation",
    "description": "Dictionary that contains the words and their respective translations.",
    "type": "object",
    "properties": {
        "dictionary": {
            "type": "string",
            "description": 'Dictionary that contains the words as keys and their respective translations as values. Provide the dictionary in the following format: {"word1": "translation1", "word2": "translation2", ...}.',
        },
    },
    "required": ["dictionary"],
}

In [12]:
system_template = """<Context>You are a helpful assistant that translates {language} words to English.</Context>

<Data Structure>The lists "translate" is an array containing {language} words or sentences.</Data Structure>

<Task>Translate the provided array "translate" to English, whereby you return a dictionary with the {language} words as keys and their English translations as values. 
The dictionary should be structured according to the provided JSON schema.
Be careful with spelling errors and do not use capital letters for adjectives.
Repeat this process in case no translations are returned or the dictionary do not follow the JSON schema.</Task>
"""

user_template = """Array "translate": 
{translate}
"""

# rescue robots and socially assistive robots
prompt_template = ChatPromptTemplate.from_messages(
    [("system", system_template), ("user", user_template)]
)


result = prompt_template.invoke({"language": "German", "translate":["Hallo", "Guten Tag"]})
print(result)

print("result:", result)
print("result.to_messages():", result.to_messages())

messages=[SystemMessage(content='<Context>You are a helpful assistant that translates German words to English.</Context>\n\n<Data Structure>The lists "translate" is an array containing German words or sentences.</Data Structure>\n\n<Task>Translate the provided array "translate" to English, whereby you return a dictionary with the German words as keys and their English translations as values. \nThe dictionary should be structured according to the provided JSON schema.\nBe careful with spelling errors and do not use capital letters for adjectives.\nRepeat this process in case no translations are returned or the dictionary do not follow the JSON schema.</Task>\n', additional_kwargs={}, response_metadata={}), HumanMessage(content='Array "translate": \n[\'Hallo\', \'Guten Tag\']\n', additional_kwargs={}, response_metadata={})]
result: messages=[SystemMessage(content='<Context>You are a helpful assistant that translates German words to English.</Context>\n\n<Data Structure>The lists "translate" is an array containing German words or sentences.</Data Structure>\n\n<Task>Translate the provided array "translate" to English, whereby you return a dictionary with the German words as keys and their English translations as values. \nThe dictionary should be structured according to the provided JSON schema.\nBe careful with spelling errors and do not use capital letters for adjectives.\nRepeat this process in case no translations are returned or the dictionary do not follow the JSON schema.</Task>\n', additional_kwargs={}, response_metadata={}), HumanMessage(content='Array "translate": \n[\'Hallo\', \'Guten Tag\']\n', additional_kwargs={}, response_metadata={})]
result.to_messages(): [SystemMessage(content='<Context>You are a helpful assistant that translates German words to English.</Context>\n\n<Data Structure>The lists "translate" is an array containing German words or sentences.</Data Structure>\n\n<Task>Translate the provided array "translate" to English, whereby you return a dictionary with the German words as keys and their English translations as values. \nThe dictionary should be structured according to the provided JSON schema.\nBe careful with spelling errors and do not use capital letters for adjectives.\nRepeat this process in case no translations are returned or the dictionary do not follow the JSON schema.</Task>\n', additional_kwargs={}, response_metadata={}), HumanMessage(content='Array "translate": \n[\'Hallo\', \'Guten Tag\']\n', additional_kwargs={}, response_metadata={})]

In [14]:
def basic_API_call(
    prompt,
    language,
    translate,
    openai_api_key,
    json_schema,
    model_name="gpt-4o",
    max_tokens=1000,
    verbose=False
):

    # prompt = PromptTemplate(template=template)
    seed = 123

    model = ChatOpenAI(model=model_name, openai_api_key=openai_api_key, max_tokens=max_tokens, model_kwargs={"seed": seed}, temperature=0.0)
       
    structured_llm = model.with_structured_output(json_schema, include_raw=True)
    chain = prompt | structured_llm

    with get_openai_callback() as cb:
        response = chain.invoke(
            {"language": language, "translate": translate}
        )
        print(cb)
    
    if verbose:
        print(f"Total Tokens: {cb.total_tokens}")
        print(f"Prompt Tokens: {cb.prompt_tokens}")
        print(f"Completion Tokens: {cb.completion_tokens}")
        print(f"Total Cost (USD): ${cb.total_cost}")
        
    return response

In [15]:
result = basic_API_call(prompt=prompt_template,
    language="German",
    translate=["Hallo", "Guten Tag", "Wie geht es dir?"],
    openai_api_key=key.openai_api_key,
    json_schema=json_schema,
    model_name="gpt-4o",
    max_tokens=1000
)

/home/fenn/Documents/env_python/lib/python3.12/site-packages/IPython/core/interactiveshell.py:3577: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  exec(code_obj, self.user_global_ns, self.user_ns)

Tokens Used: 262
	Prompt Tokens: 229
	Completion Tokens: 33
Successful Requests: 1
Total Cost (USD): $0.0009025

In [16]:
# Extract the 'parsed' section from the JSON data
parsed_section = result.get('parsed', {})
dictionary = parsed_section.get('dictionary')
    
# Convert the string back to a Python dictionary
print(type(dictionary)) 
dictionary = eval(dictionary)
print(len(dictionary.keys()))
print(dictionary)

<class 'str'>
3
{'Hallo': 'Hello', 'Guten Tag': 'Good day', 'Wie geht es dir?': 'How are you?'}

### Apply code

In [17]:
print(os.getcwd())
os.chdir("../associations_translated")
print(os.getcwd())

/home/fenn/Desktop/Publications/Article_HumanOversightAss/Article_humanOversightAssociations/Analyses/outputs/associations
/home/fenn/Desktop/Publications/Article_HumanOversightAss/Article_humanOversightAssociations/Analyses/outputs/associations_translated

In [20]:
print("Number of rows/ colums:")
print(df.shape)
print(df["response"].unique().shape)

Number of rows/ colums:
(18960, 11)
(9856,)

In [22]:
def translate_response_column(df, chunk_size=8, language="German", target_column="response"):
    """
    Translate the response column from German to English and add as response_translated.
    
    Parameters:
    - df: DataFrame containing the data
    - chunk_size: Number of texts to translate in each API call
    - language: Source language (default: German)
    - target_column: Column to translate (default: response)
    
    Returns:
    - DataFrame with added response_translated column
    """
    
    # Make a copy of the dataframe to avoid modifying the original
    df_copy = df.copy()
    
    # Check if target column exists
    if target_column not in df_copy.columns:
        print(f"Column '{target_column}' not found in DataFrame.")
        return df_copy
    
    # Get non-missing values from the response column
    non_missing_responses = df_copy[target_column].dropna()
    
    if non_missing_responses.empty:
        print(f"No non-missing values found in column '{target_column}'.")
        df_copy[f"{target_column}_translated"] = None
        return df_copy
    
    # Get unique texts to minimize API calls
    unique_texts = non_missing_responses.astype(str).unique().tolist()
    print(f"Translating {len(unique_texts)} unique texts from {language} to English...")
    
    # Dictionary to store translations
    translation_dict = {}
    counter = 0
    
    # Process texts in chunks
    for i in range(0, len(unique_texts), chunk_size):
        counter += 1
        chunk = unique_texts[i:i + chunk_size]
        print(f"Translating chunk {counter} ({len(chunk)} texts)...")
        
        try:
            result = basic_API_call(
                prompt=prompt_template,
                language=language,
                translate=chunk,
                openai_api_key=key.openai_api_key,
                json_schema=json_schema,
                model_name="gpt-4o",
                max_tokens=1000,
                verbose=False
            )
            
            parsed_section = result.get("parsed", {})
            dictionary_str = parsed_section.get("dictionary")
            
            if dictionary_str:
                # Convert string dictionary to actual dictionary
                chunk_translations = eval(dictionary_str)
                translation_dict.update(chunk_translations)
                print(f"Successfully translated chunk {counter}")
            else:
                print(f"No translations returned for chunk {counter}")
                
        except Exception as e:
            print(f"Error translating chunk {counter}: {e}")
            continue
    
    # Map translations back to the dataframe
    df_copy[f"{target_column}_translated"] = df_copy[target_column].map(translation_dict)
    
    # Report results
    successful_translations = df_copy[f"{target_column}_translated"].notna().sum()
    total_non_missing = non_missing_responses.count()
    print(f"Translation complete: {successful_translations}/{total_non_missing} responses translated")
    
    return df_copy

# Apply the translation function to the dataframe
print("Starting translation of response column...")
df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

# Display results
print("\nTranslation results:")
print(f"Original dataframe shape: {df.shape}")
print(f"Translated dataframe shape: {df_translated.shape}")
print(f"New column added: response_translated")

# Show sample of translations
if 'response_translated' in df_translated.columns:
    sample_translations = df_translated[['response', 'response_translated']].dropna().head(10)
    print("\nSample translations:")
    for idx, row in sample_translations.iterrows():
        print(f"German: {row['response']}")
        print(f"English: {row['response_translated']}")
        print("---")

Starting translation of response column...
Translating 9856 unique texts from German to English...
Translating chunk 1 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1022
	Prompt Tokens: 507
	Completion Tokens: 515
Successful Requests: 1
Total Cost (USD): $0.0064175
Successfully translated chunk 1
Translating chunk 2 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1194
	Prompt Tokens: 568
	Completion Tokens: 626
Successful Requests: 1
Total Cost (USD): $0.007679999999999999
Successfully translated chunk 2
Translating chunk 3 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1010
	Prompt Tokens: 496
	Completion Tokens: 514
Successful Requests: 1
Total Cost (USD): $0.00638
Successfully translated chunk 3
Translating chunk 4 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 988
	Prompt Tokens: 488
	Completion Tokens: 500
Successful Requests: 1
Total Cost (USD): $0.00622
Successfully translated chunk 4
Translating chunk 5 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1075
	Prompt Tokens: 520
	Completion Tokens: 555
Successful Requests: 1
Total Cost (USD): $0.00685
Successfully translated chunk 5
Translating chunk 6 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1101
	Prompt Tokens: 526
	Completion Tokens: 575
Successful Requests: 1
Total Cost (USD): $0.007065
Successfully translated chunk 6
Translating chunk 7 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1200
	Prompt Tokens: 563
	Completion Tokens: 637
Successful Requests: 1
Total Cost (USD): $0.0077775000000000006
Successfully translated chunk 7
Translating chunk 8 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1048
	Prompt Tokens: 512
	Completion Tokens: 536
Successful Requests: 1
Total Cost (USD): $0.00664
Successfully translated chunk 8
Translating chunk 9 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1067
	Prompt Tokens: 519
	Completion Tokens: 548
Successful Requests: 1
Total Cost (USD): $0.0067775000000000005
Successfully translated chunk 9
Translating chunk 10 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1146
	Prompt Tokens: 549
	Completion Tokens: 597
Successful Requests: 1
Total Cost (USD): $0.0073425
Successfully translated chunk 10
Translating chunk 11 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1153
	Prompt Tokens: 552
	Completion Tokens: 601
Successful Requests: 1
Total Cost (USD): $0.00739
Successfully translated chunk 11
Translating chunk 12 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1068
	Prompt Tokens: 514
	Completion Tokens: 554
Successful Requests: 1
Total Cost (USD): $0.006825000000000001
Successfully translated chunk 12
Translating chunk 13 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1088
	Prompt Tokens: 529
	Completion Tokens: 559
Successful Requests: 1
Total Cost (USD): $0.0069125
Successfully translated chunk 13
Translating chunk 14 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1154
	Prompt Tokens: 546
	Completion Tokens: 608
Successful Requests: 1
Total Cost (USD): $0.007445
Successfully translated chunk 14
Translating chunk 15 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1207
	Prompt Tokens: 573
	Completion Tokens: 634
Successful Requests: 1
Total Cost (USD): $0.0077725
Successfully translated chunk 15
Translating chunk 16 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1014
	Prompt Tokens: 499
	Completion Tokens: 515
Successful Requests: 1
Total Cost (USD): $0.0063975
Successfully translated chunk 16
Translating chunk 17 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1126
	Prompt Tokens: 534
	Completion Tokens: 592
Successful Requests: 1
Total Cost (USD): $0.007255
Successfully translated chunk 17
Translating chunk 18 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1146
	Prompt Tokens: 542
	Completion Tokens: 604
Successful Requests: 1
Total Cost (USD): $0.0073950000000000005
Successfully translated chunk 18
Translating chunk 19 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1144
	Prompt Tokens: 544
	Completion Tokens: 600
Successful Requests: 1
Total Cost (USD): $0.00736
Successfully translated chunk 19
Translating chunk 20 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1102
	Prompt Tokens: 522
	Completion Tokens: 580
Successful Requests: 1
Total Cost (USD): $0.007105
Successfully translated chunk 20
Translating chunk 21 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1057
	Prompt Tokens: 511
	Completion Tokens: 546
Successful Requests: 1
Total Cost (USD): $0.0067375
Successfully translated chunk 21
Translating chunk 22 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1111
	Prompt Tokens: 528
	Completion Tokens: 583
Successful Requests: 1
Total Cost (USD): $0.00715
Successfully translated chunk 22
Translating chunk 23 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1183
	Prompt Tokens: 553
	Completion Tokens: 630
Successful Requests: 1
Total Cost (USD): $0.0076825
Successfully translated chunk 23
Translating chunk 24 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1128
	Prompt Tokens: 537
	Completion Tokens: 591
Successful Requests: 1
Total Cost (USD): $0.007252499999999999
Successfully translated chunk 24
Translating chunk 25 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1149
	Prompt Tokens: 550
	Completion Tokens: 599
Successful Requests: 1
Total Cost (USD): $0.007365
Successfully translated chunk 25
Translating chunk 26 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1121
	Prompt Tokens: 541
	Completion Tokens: 580
Successful Requests: 1
Total Cost (USD): $0.0071525
Successfully translated chunk 26
Translating chunk 27 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1078
	Prompt Tokens: 523
	Completion Tokens: 555
Successful Requests: 1
Total Cost (USD): $0.006857500000000001
Successfully translated chunk 27
Translating chunk 28 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1112
	Prompt Tokens: 533
	Completion Tokens: 579
Successful Requests: 1
Total Cost (USD): $0.0071225
Successfully translated chunk 28
Translating chunk 29 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1128
	Prompt Tokens: 534
	Completion Tokens: 594
Successful Requests: 1
Total Cost (USD): $0.007275
Successfully translated chunk 29
Translating chunk 30 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1079
	Prompt Tokens: 525
	Completion Tokens: 554
Successful Requests: 1
Total Cost (USD): $0.006852500000000001
Successfully translated chunk 30
Translating chunk 31 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1078
	Prompt Tokens: 525
	Completion Tokens: 553
Successful Requests: 1
Total Cost (USD): $0.0068425000000000005
Successfully translated chunk 31
Translating chunk 32 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1088
	Prompt Tokens: 525
	Completion Tokens: 563
Successful Requests: 1
Total Cost (USD): $0.0069425
Successfully translated chunk 32
Translating chunk 33 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1261
	Prompt Tokens: 585
	Completion Tokens: 676
Successful Requests: 1
Total Cost (USD): $0.0082225
Successfully translated chunk 33
Translating chunk 34 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1207
	Prompt Tokens: 569
	Completion Tokens: 638
Successful Requests: 1
Total Cost (USD): $0.0078025
Successfully translated chunk 34
Translating chunk 35 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1119
	Prompt Tokens: 538
	Completion Tokens: 581
Successful Requests: 1
Total Cost (USD): $0.007155
Successfully translated chunk 35
Translating chunk 36 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1250
	Prompt Tokens: 592
	Completion Tokens: 658
Successful Requests: 1
Total Cost (USD): $0.008060000000000001
Successfully translated chunk 36
Translating chunk 37 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1171
	Prompt Tokens: 555
	Completion Tokens: 616
Successful Requests: 1
Total Cost (USD): $0.0075474999999999995
Successfully translated chunk 37
Translating chunk 38 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1106
	Prompt Tokens: 530
	Completion Tokens: 576
Successful Requests: 1
Total Cost (USD): $0.007084999999999999
Successfully translated chunk 38
Translating chunk 39 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1160
	Prompt Tokens: 539
	Completion Tokens: 621
Successful Requests: 1
Total Cost (USD): $0.0075575
Successfully translated chunk 39
Translating chunk 40 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1224
	Prompt Tokens: 577
	Completion Tokens: 647
Successful Requests: 1
Total Cost (USD): $0.0079125
Successfully translated chunk 40
Translating chunk 41 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1180
	Prompt Tokens: 558
	Completion Tokens: 622
Successful Requests: 1
Total Cost (USD): $0.007615
Successfully translated chunk 41
Translating chunk 42 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1113
	Prompt Tokens: 533
	Completion Tokens: 580
Successful Requests: 1
Total Cost (USD): $0.0071325
Successfully translated chunk 42
Translating chunk 43 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1269
	Prompt Tokens: 593
	Completion Tokens: 676
Successful Requests: 1
Total Cost (USD): $0.0082425
Successfully translated chunk 43
Translating chunk 44 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1011
	Prompt Tokens: 496
	Completion Tokens: 515
Successful Requests: 1
Total Cost (USD): $0.00639
Successfully translated chunk 44
Translating chunk 45 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1216
	Prompt Tokens: 566
	Completion Tokens: 650
Successful Requests: 1
Total Cost (USD): $0.007915
Successfully translated chunk 45
Translating chunk 46 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1117
	Prompt Tokens: 537
	Completion Tokens: 580
Successful Requests: 1
Total Cost (USD): $0.0071424999999999995
Successfully translated chunk 46
Translating chunk 47 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1256
	Prompt Tokens: 582
	Completion Tokens: 674
Successful Requests: 1
Total Cost (USD): $0.008195000000000001
Successfully translated chunk 47
Translating chunk 48 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1176
	Prompt Tokens: 556
	Completion Tokens: 620
Successful Requests: 1
Total Cost (USD): $0.0075899999999999995
Successfully translated chunk 48
Translating chunk 49 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1120
	Prompt Tokens: 536
	Completion Tokens: 584
Successful Requests: 1
Total Cost (USD): $0.00718
Successfully translated chunk 49
Translating chunk 50 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1003
	Prompt Tokens: 491
	Completion Tokens: 512
Successful Requests: 1
Total Cost (USD): $0.006347500000000001
Successfully translated chunk 50
Translating chunk 51 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1099
	Prompt Tokens: 534
	Completion Tokens: 565
Successful Requests: 1
Total Cost (USD): $0.006985
Successfully translated chunk 51
Translating chunk 52 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1176
	Prompt Tokens: 557
	Completion Tokens: 619
Successful Requests: 1
Total Cost (USD): $0.007582500000000001
Successfully translated chunk 52
Translating chunk 53 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1174
	Prompt Tokens: 558
	Completion Tokens: 616
Successful Requests: 1
Total Cost (USD): $0.007555
Successfully translated chunk 53
Translating chunk 54 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1034
	Prompt Tokens: 505
	Completion Tokens: 529
Successful Requests: 1
Total Cost (USD): $0.0065525
Successfully translated chunk 54
Translating chunk 55 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1057
	Prompt Tokens: 507
	Completion Tokens: 550
Successful Requests: 1
Total Cost (USD): $0.006767500000000001
Successfully translated chunk 55
Translating chunk 56 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 999
	Prompt Tokens: 528
	Completion Tokens: 471
Successful Requests: 1
Total Cost (USD): $0.00603
Successfully translated chunk 56
Translating chunk 57 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1089
	Prompt Tokens: 524
	Completion Tokens: 565
Successful Requests: 1
Total Cost (USD): $0.00696
Successfully translated chunk 57
Translating chunk 58 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1009
	Prompt Tokens: 491
	Completion Tokens: 518
Successful Requests: 1
Total Cost (USD): $0.006407500000000001
Successfully translated chunk 58
Translating chunk 59 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1137
	Prompt Tokens: 538
	Completion Tokens: 599
Successful Requests: 1
Total Cost (USD): $0.0073349999999999995
Successfully translated chunk 59
Translating chunk 60 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1116
	Prompt Tokens: 523
	Completion Tokens: 593
Successful Requests: 1
Total Cost (USD): $0.007237499999999999
Successfully translated chunk 60
Translating chunk 61 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1154
	Prompt Tokens: 550
	Completion Tokens: 604
Successful Requests: 1
Total Cost (USD): $0.007415000000000001
Successfully translated chunk 61
Translating chunk 62 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1131
	Prompt Tokens: 543
	Completion Tokens: 588
Successful Requests: 1
Total Cost (USD): $0.0072375
Successfully translated chunk 62
Translating chunk 63 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1189
	Prompt Tokens: 562
	Completion Tokens: 627
Successful Requests: 1
Total Cost (USD): $0.007675
Successfully translated chunk 63
Translating chunk 64 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1242
	Prompt Tokens: 583
	Completion Tokens: 659
Successful Requests: 1
Total Cost (USD): $0.0080475
Successfully translated chunk 64
Translating chunk 65 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1071
	Prompt Tokens: 517
	Completion Tokens: 554
Successful Requests: 1
Total Cost (USD): $0.006832500000000001
Successfully translated chunk 65
Translating chunk 66 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1179
	Prompt Tokens: 555
	Completion Tokens: 624
Successful Requests: 1
Total Cost (USD): $0.0076275
Successfully translated chunk 66
Translating chunk 67 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1082
	Prompt Tokens: 516
	Completion Tokens: 566
Successful Requests: 1
Total Cost (USD): $0.00695
Successfully translated chunk 67
Translating chunk 68 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1084
	Prompt Tokens: 521
	Completion Tokens: 563
Successful Requests: 1
Total Cost (USD): $0.006932499999999999
Successfully translated chunk 68
Translating chunk 69 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1108
	Prompt Tokens: 534
	Completion Tokens: 574
Successful Requests: 1
Total Cost (USD): $0.007075
Successfully translated chunk 69
Translating chunk 70 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1154
	Prompt Tokens: 544
	Completion Tokens: 610
Successful Requests: 1
Total Cost (USD): $0.0074600000000000005
Successfully translated chunk 70
Translating chunk 71 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1078
	Prompt Tokens: 514
	Completion Tokens: 564
Successful Requests: 1
Total Cost (USD): $0.006924999999999999
Successfully translated chunk 71
Translating chunk 72 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1158
	Prompt Tokens: 547
	Completion Tokens: 611
Successful Requests: 1
Total Cost (USD): $0.0074775
Successfully translated chunk 72
Translating chunk 73 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1094
	Prompt Tokens: 509
	Completion Tokens: 585
Successful Requests: 1
Total Cost (USD): $0.0071225
Successfully translated chunk 73
Translating chunk 74 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1140
	Prompt Tokens: 543
	Completion Tokens: 597
Successful Requests: 1
Total Cost (USD): $0.0073275
Successfully translated chunk 74
Translating chunk 75 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1103
	Prompt Tokens: 518
	Completion Tokens: 585
Successful Requests: 1
Total Cost (USD): $0.007145
Successfully translated chunk 75
Translating chunk 76 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1096
	Prompt Tokens: 519
	Completion Tokens: 577
Successful Requests: 1
Total Cost (USD): $0.0070675
Successfully translated chunk 76
Translating chunk 77 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1219
	Prompt Tokens: 573
	Completion Tokens: 646
Successful Requests: 1
Total Cost (USD): $0.0078925
Successfully translated chunk 77
Translating chunk 78 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1210
	Prompt Tokens: 570
	Completion Tokens: 640
Successful Requests: 1
Total Cost (USD): $0.007825
Successfully translated chunk 78
Translating chunk 79 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1284
	Prompt Tokens: 603
	Completion Tokens: 681
Successful Requests: 1
Total Cost (USD): $0.0083175
Successfully translated chunk 79
Translating chunk 80 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1153
	Prompt Tokens: 548
	Completion Tokens: 605
Successful Requests: 1
Total Cost (USD): $0.0074199999999999995
Successfully translated chunk 80
Translating chunk 81 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1324
	Prompt Tokens: 612
	Completion Tokens: 712
Successful Requests: 1
Total Cost (USD): $0.00865
Successfully translated chunk 81
Translating chunk 82 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1137
	Prompt Tokens: 543
	Completion Tokens: 594
Successful Requests: 1
Total Cost (USD): $0.0072975
Successfully translated chunk 82
Translating chunk 83 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1186
	Prompt Tokens: 559
	Completion Tokens: 627
Successful Requests: 1
Total Cost (USD): $0.007667500000000001
Successfully translated chunk 83
Translating chunk 84 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1115
	Prompt Tokens: 538
	Completion Tokens: 577
Successful Requests: 1
Total Cost (USD): $0.007115
Successfully translated chunk 84
Translating chunk 85 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1045
	Prompt Tokens: 508
	Completion Tokens: 537
Successful Requests: 1
Total Cost (USD): $0.006640000000000001
Successfully translated chunk 85
Translating chunk 86 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1142
	Prompt Tokens: 546
	Completion Tokens: 596
Successful Requests: 1
Total Cost (USD): $0.007325
Successfully translated chunk 86
Translating chunk 87 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1055
	Prompt Tokens: 508
	Completion Tokens: 547
Successful Requests: 1
Total Cost (USD): $0.006740000000000001
Successfully translated chunk 87
Translating chunk 88 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1098
	Prompt Tokens: 527
	Completion Tokens: 571
Successful Requests: 1
Total Cost (USD): $0.0070275
Successfully translated chunk 88
Translating chunk 89 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1091
	Prompt Tokens: 527
	Completion Tokens: 564
Successful Requests: 1
Total Cost (USD): $0.006957499999999999
Successfully translated chunk 89
Translating chunk 90 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1000
	Prompt Tokens: 489
	Completion Tokens: 511
Successful Requests: 1
Total Cost (USD): $0.0063325
Successfully translated chunk 90
Translating chunk 91 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1052
	Prompt Tokens: 505
	Completion Tokens: 547
Successful Requests: 1
Total Cost (USD): $0.006732500000000001
Successfully translated chunk 91
Translating chunk 92 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1114
	Prompt Tokens: 531
	Completion Tokens: 583
Successful Requests: 1
Total Cost (USD): $0.007157500000000001
Successfully translated chunk 92
Translating chunk 93 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1183
	Prompt Tokens: 559
	Completion Tokens: 624
Successful Requests: 1
Total Cost (USD): $0.0076375
Successfully translated chunk 93
Translating chunk 94 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1203
	Prompt Tokens: 569
	Completion Tokens: 634
Successful Requests: 1
Total Cost (USD): $0.0077625
Successfully translated chunk 94
Translating chunk 95 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1140
	Prompt Tokens: 540
	Completion Tokens: 600
Successful Requests: 1
Total Cost (USD): $0.007350000000000001
Successfully translated chunk 95
Translating chunk 96 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1184
	Prompt Tokens: 555
	Completion Tokens: 629
Successful Requests: 1
Total Cost (USD): $0.0076775
Successfully translated chunk 96
Translating chunk 97 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1147
	Prompt Tokens: 544
	Completion Tokens: 603
Successful Requests: 1
Total Cost (USD): $0.00739
Successfully translated chunk 97
Translating chunk 98 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1214
	Prompt Tokens: 563
	Completion Tokens: 651
Successful Requests: 1
Total Cost (USD): $0.007917500000000001
Successfully translated chunk 98
Translating chunk 99 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1173
	Prompt Tokens: 551
	Completion Tokens: 622
Successful Requests: 1
Total Cost (USD): $0.0075975
Successfully translated chunk 99
Translating chunk 100 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1133
	Prompt Tokens: 541
	Completion Tokens: 592
Successful Requests: 1
Total Cost (USD): $0.0072725
Successfully translated chunk 100
Translating chunk 101 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1162
	Prompt Tokens: 550
	Completion Tokens: 612
Successful Requests: 1
Total Cost (USD): $0.007495000000000001
Successfully translated chunk 101
Translating chunk 102 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1144
	Prompt Tokens: 545
	Completion Tokens: 599
Successful Requests: 1
Total Cost (USD): $0.0073525
Successfully translated chunk 102
Translating chunk 103 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1264
	Prompt Tokens: 584
	Completion Tokens: 680
Successful Requests: 1
Total Cost (USD): $0.00826
Successfully translated chunk 103
Translating chunk 104 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1151
	Prompt Tokens: 541
	Completion Tokens: 610
Successful Requests: 1
Total Cost (USD): $0.007452500000000001
Successfully translated chunk 104
Translating chunk 105 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1060
	Prompt Tokens: 507
	Completion Tokens: 553
Successful Requests: 1
Total Cost (USD): $0.0067975
Successfully translated chunk 105
Translating chunk 106 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1126
	Prompt Tokens: 537
	Completion Tokens: 589
Successful Requests: 1
Total Cost (USD): $0.007232499999999999
Successfully translated chunk 106
Translating chunk 107 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1234
	Prompt Tokens: 569
	Completion Tokens: 665
Successful Requests: 1
Total Cost (USD): $0.0080725
Successfully translated chunk 107
Translating chunk 108 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1123
	Prompt Tokens: 536
	Completion Tokens: 587
Successful Requests: 1
Total Cost (USD): $0.00721
Successfully translated chunk 108
Translating chunk 109 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1328
	Prompt Tokens: 612
	Completion Tokens: 716
Successful Requests: 1
Total Cost (USD): $0.00869
Successfully translated chunk 109
Translating chunk 110 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1205
	Prompt Tokens: 563
	Completion Tokens: 642
Successful Requests: 1
Total Cost (USD): $0.007827500000000001
Successfully translated chunk 110
Translating chunk 111 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1121
	Prompt Tokens: 530
	Completion Tokens: 591
Successful Requests: 1
Total Cost (USD): $0.007234999999999999
Successfully translated chunk 111
Translating chunk 112 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1097
	Prompt Tokens: 534
	Completion Tokens: 563
Successful Requests: 1
Total Cost (USD): $0.006965
Successfully translated chunk 112
Translating chunk 113 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1255
	Prompt Tokens: 582
	Completion Tokens: 673
Successful Requests: 1
Total Cost (USD): $0.008185000000000001
Successfully translated chunk 113
Translating chunk 114 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1121
	Prompt Tokens: 540
	Completion Tokens: 581
Successful Requests: 1
Total Cost (USD): $0.00716
Successfully translated chunk 114
Translating chunk 115 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1286
	Prompt Tokens: 599
	Completion Tokens: 687
Successful Requests: 1
Total Cost (USD): $0.008367500000000002
Successfully translated chunk 115
Translating chunk 116 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1191
	Prompt Tokens: 556
	Completion Tokens: 635
Successful Requests: 1
Total Cost (USD): $0.00774
Successfully translated chunk 116
Translating chunk 117 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1640
	Prompt Tokens: 741
	Completion Tokens: 899
Successful Requests: 1
Total Cost (USD): $0.0108425
Successfully translated chunk 117
Translating chunk 118 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1155
	Prompt Tokens: 545
	Completion Tokens: 610
Successful Requests: 1
Total Cost (USD): $0.0074625
Successfully translated chunk 118
Translating chunk 119 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1178
	Prompt Tokens: 556
	Completion Tokens: 622
Successful Requests: 1
Total Cost (USD): $0.0076100000000000004
Successfully translated chunk 119
Translating chunk 120 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1102
	Prompt Tokens: 530
	Completion Tokens: 572
Successful Requests: 1
Total Cost (USD): $0.007044999999999999
Successfully translated chunk 120
Translating chunk 121 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1287
	Prompt Tokens: 589
	Completion Tokens: 698
Successful Requests: 1
Total Cost (USD): $0.0084525
Successfully translated chunk 121
Translating chunk 122 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1090
	Prompt Tokens: 527
	Completion Tokens: 563
Successful Requests: 1
Total Cost (USD): $0.0069475
Successfully translated chunk 122
Translating chunk 123 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1186
	Prompt Tokens: 563
	Completion Tokens: 623
Successful Requests: 1
Total Cost (USD): $0.0076375
Successfully translated chunk 123
Translating chunk 124 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1215
	Prompt Tokens: 567
	Completion Tokens: 648
Successful Requests: 1
Total Cost (USD): $0.0078975
Successfully translated chunk 124
Translating chunk 125 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1134
	Prompt Tokens: 544
	Completion Tokens: 590
Successful Requests: 1
Total Cost (USD): $0.00726
Successfully translated chunk 125
Translating chunk 126 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1227
	Prompt Tokens: 563
	Completion Tokens: 664
Successful Requests: 1
Total Cost (USD): $0.008047499999999999
Successfully translated chunk 126
Translating chunk 127 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1147
	Prompt Tokens: 542
	Completion Tokens: 605
Successful Requests: 1
Total Cost (USD): $0.007405
Successfully translated chunk 127
Translating chunk 128 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1144
	Prompt Tokens: 545
	Completion Tokens: 599
Successful Requests: 1
Total Cost (USD): $0.0073525
Successfully translated chunk 128
Translating chunk 129 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1210
	Prompt Tokens: 573
	Completion Tokens: 637
Successful Requests: 1
Total Cost (USD): $0.0078025
Successfully translated chunk 129
Translating chunk 130 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1100
	Prompt Tokens: 531
	Completion Tokens: 569
Successful Requests: 1
Total Cost (USD): $0.007017499999999999
Successfully translated chunk 130
Translating chunk 131 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1167
	Prompt Tokens: 554
	Completion Tokens: 613
Successful Requests: 1
Total Cost (USD): $0.007515
Successfully translated chunk 131
Translating chunk 132 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1210
	Prompt Tokens: 575
	Completion Tokens: 635
Successful Requests: 1
Total Cost (USD): $0.007787500000000001
Successfully translated chunk 132
Translating chunk 133 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1228
	Prompt Tokens: 569
	Completion Tokens: 659
Successful Requests: 1
Total Cost (USD): $0.0080125
Successfully translated chunk 133
Translating chunk 134 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1131
	Prompt Tokens: 539
	Completion Tokens: 592
Successful Requests: 1
Total Cost (USD): $0.0072675
Successfully translated chunk 134
Translating chunk 135 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1147
	Prompt Tokens: 536
	Completion Tokens: 611
Successful Requests: 1
Total Cost (USD): $0.00745
Successfully translated chunk 135
Translating chunk 136 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1129
	Prompt Tokens: 539
	Completion Tokens: 590
Successful Requests: 1
Total Cost (USD): $0.0072475000000000005
Successfully translated chunk 136
Translating chunk 137 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1181
	Prompt Tokens: 557
	Completion Tokens: 624
Successful Requests: 1
Total Cost (USD): $0.0076325
Successfully translated chunk 137
Translating chunk 138 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1232
	Prompt Tokens: 574
	Completion Tokens: 658
Successful Requests: 1
Total Cost (USD): $0.008015000000000001
Successfully translated chunk 138
Translating chunk 139 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1202
	Prompt Tokens: 562
	Completion Tokens: 640
Successful Requests: 1
Total Cost (USD): $0.007805
Successfully translated chunk 139
Translating chunk 140 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1127
	Prompt Tokens: 527
	Completion Tokens: 600
Successful Requests: 1
Total Cost (USD): $0.0073175
Successfully translated chunk 140
Translating chunk 141 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1128
	Prompt Tokens: 538
	Completion Tokens: 590
Successful Requests: 1
Total Cost (USD): $0.007245
Successfully translated chunk 141
Translating chunk 142 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1112
	Prompt Tokens: 532
	Completion Tokens: 580
Successful Requests: 1
Total Cost (USD): $0.007129999999999999
Successfully translated chunk 142
Translating chunk 143 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1256
	Prompt Tokens: 580
	Completion Tokens: 676
Successful Requests: 1
Total Cost (USD): $0.00821
Successfully translated chunk 143
Translating chunk 144 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1329
	Prompt Tokens: 617
	Completion Tokens: 712
Successful Requests: 1
Total Cost (USD): $0.0086625
Successfully translated chunk 144
Translating chunk 145 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1183
	Prompt Tokens: 556
	Completion Tokens: 627
Successful Requests: 1
Total Cost (USD): $0.00766
Successfully translated chunk 145
Translating chunk 146 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1167
	Prompt Tokens: 543
	Completion Tokens: 624
Successful Requests: 1
Total Cost (USD): $0.0075975
Successfully translated chunk 146
Translating chunk 147 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1152
	Prompt Tokens: 550
	Completion Tokens: 602
Successful Requests: 1
Total Cost (USD): $0.0073950000000000005
Successfully translated chunk 147
Translating chunk 148 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1057
	Prompt Tokens: 509
	Completion Tokens: 548
Successful Requests: 1
Total Cost (USD): $0.006752500000000001
Successfully translated chunk 148
Translating chunk 149 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1150
	Prompt Tokens: 540
	Completion Tokens: 610
Successful Requests: 1
Total Cost (USD): $0.00745
Successfully translated chunk 149
Translating chunk 150 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1119
	Prompt Tokens: 535
	Completion Tokens: 584
Successful Requests: 1
Total Cost (USD): $0.0071775
Successfully translated chunk 150
Translating chunk 151 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1185
	Prompt Tokens: 561
	Completion Tokens: 624
Successful Requests: 1
Total Cost (USD): $0.0076425
Successfully translated chunk 151
Translating chunk 152 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1231
	Prompt Tokens: 574
	Completion Tokens: 657
Successful Requests: 1
Total Cost (USD): $0.008005
Successfully translated chunk 152
Translating chunk 153 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1216
	Prompt Tokens: 567
	Completion Tokens: 649
Successful Requests: 1
Total Cost (USD): $0.0079075
Successfully translated chunk 153
Translating chunk 154 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1151
	Prompt Tokens: 544
	Completion Tokens: 607
Successful Requests: 1
Total Cost (USD): $0.00743
Successfully translated chunk 154
Translating chunk 155 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1154
	Prompt Tokens: 544
	Completion Tokens: 610
Successful Requests: 1
Total Cost (USD): $0.0074600000000000005
Successfully translated chunk 155
Translating chunk 156 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1239
	Prompt Tokens: 575
	Completion Tokens: 664
Successful Requests: 1
Total Cost (USD): $0.0080775
Successfully translated chunk 156
Translating chunk 157 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1153
	Prompt Tokens: 543
	Completion Tokens: 610
Successful Requests: 1
Total Cost (USD): $0.007457500000000001
Successfully translated chunk 157
Translating chunk 158 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1237
	Prompt Tokens: 582
	Completion Tokens: 655
Successful Requests: 1
Total Cost (USD): $0.008005
Successfully translated chunk 158
Translating chunk 159 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1200
	Prompt Tokens: 561
	Completion Tokens: 639
Successful Requests: 1
Total Cost (USD): $0.0077925
Successfully translated chunk 159
Translating chunk 160 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1228
	Prompt Tokens: 574
	Completion Tokens: 654
Successful Requests: 1
Total Cost (USD): $0.007975000000000001
Successfully translated chunk 160
Translating chunk 161 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1216
	Prompt Tokens: 567
	Completion Tokens: 649
Successful Requests: 1
Total Cost (USD): $0.0079075
Successfully translated chunk 161
Translating chunk 162 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1163
	Prompt Tokens: 553
	Completion Tokens: 610
Successful Requests: 1
Total Cost (USD): $0.0074825000000000004
Successfully translated chunk 162
Translating chunk 163 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1359
	Prompt Tokens: 621
	Completion Tokens: 738
Successful Requests: 1
Total Cost (USD): $0.0089325
Successfully translated chunk 163
Translating chunk 164 (60 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 1083
	Prompt Tokens: 524
	Completion Tokens: 559
Successful Requests: 1
Total Cost (USD): $0.006900000000000001
Successfully translated chunk 164
Translating chunk 165 (16 texts)...

/tmp/ipykernel_200739/802118741.py:84: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
  df_translated = translate_response_column(df, chunk_size=60, language="German", target_column="response")

Tokens Used: 450
	Prompt Tokens: 296
	Completion Tokens: 154
Successful Requests: 1
Total Cost (USD): $0.00228
Successfully translated chunk 165
Translation complete: 18495/18960 responses translated

Translation results:
Original dataframe shape: (18960, 11)
Translated dataframe shape: (18960, 12)
New column added: response_translated

Sample translations:
German: Richtig
English: correct
---
German: Fortschritt
English: progress
---
German: Zukunft
English: future
---
German: Zusammenspiel
English: interaction
---
German: Verbesserung
English: improvement
---
German: Moralisch
English: moral
---
German: Bessere Überlebenschancen
English: better survival chances
---
German: Früherkennung
English: early detection
---
German: Gleichheit
English: equality
---
German: Niveau Steigerung
English: level increase
---

In [33]:
backup_df_translated = df_translated
df_translated

,participant_id,study_condition,gender,age,cue,valence,response,response_position,response_level,timestamp,time_diff_sec,response_translated
0,6914df322c0ecd3bdadf7251,Diagnostic,male,33.0,Diagnostic,6.0,Richtig,1,1,2025-11-24 08:16:27.162,0.000,correct
1,6914df322c0ecd3bdadf7251,Diagnostic,male,33.0,Diagnostic,7.0,Fortschritt,2,1,2025-11-24 08:16:35.087,7.925,progress
2,6914df322c0ecd3bdadf7251,Diagnostic,male,33.0,Diagnostic,5.0,Zukunft,3,1,2025-11-24 08:16:38.866,11.704,future
3,6914df322c0ecd3bdadf7251,Diagnostic,male,33.0,Diagnostic,6.0,Zusammenspiel,4,1,2025-11-24 08:16:46.704,19.542,interaction
4,6914df322c0ecd3bdadf7251,Diagnostic,male,33.0,Diagnostic,7.0,Verbesserung,5,1,2025-11-24 08:16:54.584,27.422,improvement
...,...,...,...,...,...,...,...,...,...,...,...,...
18955,69273d7a43eca09e260bac35,CourtDecision,female,22.0,Fragwürdig,NaN,wieso,1,2,2026-02-11 17:13:58.343,443.097,NaN
18956,69273d7a43eca09e260bac35,CourtDecision,female,22.0,Fragwürdig,NaN,künstlich,2,2,2026-02-11 17:14:07.421,452.175,artificial
18957,69273d7a43eca09e260bac35,CourtDecision,female,22.0,Fragwürdig,NaN,unsicher,3,2,2026-02-11 17:14:15.217,459.971,NaN
18958,69273d7a43eca09e260bac35,CourtDecision,female,22.0,Fragwürdig,NaN,schlecht,4,2,2026-02-11 17:14:22.131,466.885,bad
18959,69273d7a43eca09e260bac35,CourtDecision,female,22.0,Fragwürdig,NaN,naja,5,2,2026-02-11 17:14:26.600,471.354,well

In [40]:
cols = ["response", "response_translated"]
missing_counts = df_translated[cols].isna().sum()
missing_pct = df_translated[cols].isna().mean() * 100

print("Missing counts and percentages (of rows):")
for c in cols:
    print(f"{c}: {missing_counts[c]} / {len(df_translated)} ({missing_pct[c]:.2f}%)")

# Show up to 10 examples of rows with missing values for each column in `cols`
for c in cols:
    miss = df_translated[df_translated[c].isna()]
    n = len(miss)
    print(f"\nColumn '{c}' — missing {n}/{len(df_translated)} rows ({missing_pct[c]:.2f}%)")
    if n == 0:
        print("  (none)")
    else:
        # show context columns and up to 10 examples
        print(miss.loc[:, ['participant_id', 'cue', 'response', 'response_translated']].head(10).to_string(index=True))

Missing counts and percentages (of rows):
response: 0 / 18960 (0.00%)
response_translated: 190 / 18960 (1.00%)

Column 'response' — missing 0/18960 rows (0.00%)
  (none)

Column 'response_translated' — missing 190/18960 rows (1.00%)
                 participant_id                    cue                response response_translated
11586  6931b0a54a97529bbae235d9               Schlecht  keine Kritikfähigkeit                  NaN
11590  6931b0a54a97529bbae235d9                Ungenau        KI hallizuniert                  NaN
11595  6931b0a54a97529bbae235d9  Zu positive bewertung            Verschönung                  NaN
11596  6931b0a54a97529bbae235d9  Zu positive bewertung            Ehrlichkeit                  NaN
11598  6931b0a54a97529bbae235d9  Zu positive bewertung       Kritikunfähikeit                  NaN
11611  693087d06909b0ac1158bc5d                Grading             Vorsichtig                  NaN
11612  693087d06909b0ac1158bc5d                Grading                 Regeln                  NaN
11613  693087d06909b0ac1158bc5d                Grading             Misstrauen                  NaN
11615  693087d06909b0ac1158bc5d              Kontrolle               Abstrakt                  NaN
11617  693087d06909b0ac1158bc5d              Kontrolle                Digital                  NaN

In [32]:
# Save df_translated to current working directory as XLSX and CSV
filename_base = "ass_study_translated"
xlsx_path = os.path.join(os.getcwd(), f"{filename_base}.xlsx")
csv_path = os.path.join(os.getcwd(), f"{filename_base}.csv")

try:
    df_translated.to_excel(xlsx_path, index=False)
    print(f"Saved Excel: {xlsx_path} ({df_translated.shape[0]} rows, {df_translated.shape[1]} cols)")
except Exception as e:
    print(f"Error saving Excel: {e}")

try:
    df_translated.to_csv(csv_path, index=False)
    print(f"Saved CSV:   {csv_path} ({df_translated.shape[0]} rows, {df_translated.shape[1]} cols)")
except Exception as e:
    print(f"Error saving CSV: {e}")

Saved Excel: /home/fenn/Desktop/Publications/Article_HumanOversightAss/Article_humanOversightAssociations/Analyses/outputs/associations_translated/ass_study_translated.xlsx (18960 rows, 12 cols)
Saved CSV:   /home/fenn/Desktop/Publications/Article_HumanOversightAss/Article_humanOversightAssociations/Analyses/outputs/associations_translated/ass_study_translated.csv (18960 rows, 12 cols)